project:
  type: website
  output-dir: docs

website:
  title: "Lia Noel Crocker"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: media.qmd
        text: Media

format:
  html:
    theme: vapor
    css: styles.css
    toc: true



